
name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '40 11 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '1 day'
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5
